"""ondelete

Revision ID: 2b5cef8fd5ec
Revises: 2984b5f83321
Create Date: 2023-03-12 13:14:30.228043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5cef8fd5ec'
down_revision = '2984b5f83321'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_invited_event_id_fkey', 'event_invited', type_='foreignkey')
    op.create_foreign_key(None, 'event_invited', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_invited', type_='foreignkey')
    op.create_foreign_key('event_invited_event_id_fkey', 'event_invited', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
