"""ondelete all

Revision ID: c4abeb7d293b
Revises: 2b5cef8fd5ec
Create Date: 2023-03-12 13:18:03.028302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4abeb7d293b'
down_revision = '2b5cef8fd5ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_owner_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['owner'], ['id'], ondelete='CASCADE')
    op.drop_constraint('event_invited_invited_id_fkey', 'event_invited', type_='foreignkey')
    op.create_foreign_key(None, 'event_invited', 'user', ['invited_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_invited', type_='foreignkey')
    op.create_foreign_key('event_invited_invited_id_fkey', 'event_invited', 'user', ['invited_id'], ['id'])
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_owner_fkey', 'event', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###
